---
version: "2.1"
services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:arm64v8-latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=502
      - PGID=20
      - TZ=Europe/London
      - SERVERURL=61.47.105.20 #optional
      - SERVERPORT=443 #optional
      - PEERS=4 #optional
      - PEERDNS=auto #optional
      # - INTERNAL_SUBNET=10.13.13.0 #optional
      - ALLOWEDIPS=0.0.0.0/0 #optional
      - PERSISTENTKEEPALIVE_PEERS=all
      - LOG_CONFS=false #optional
    volumes:
      - /Users/dhadaroopkae/docker-wireguard/config:/config
      - /lib/modules:/lib/modules #optional
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: always
